/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.school_management;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author az
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelwelcome = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(null);

        labelwelcome.setBackground(new java.awt.Color(0, 0, 153));
        labelwelcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelwelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelwelcome.setText("SCHOOL ADMIN LOGIN");
        labelwelcome.setOpaque(true);
        getContentPane().add(labelwelcome);
        labelwelcome.setBounds(90, 70, 470, 60);

        labelUserName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(204, 204, 204));
        labelUserName.setText("USERNAME");
        getContentPane().add(labelUserName);
        labelUserName.setBounds(90, 170, 80, 20);

        txtUsername.setToolTipText("");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(190, 160, 370, 30);

        labelPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(204, 204, 204));
        labelPassword.setText("PASSWORD");
        getContentPane().add(labelPassword);
        labelPassword.setBounds(90, 220, 80, 20);

        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(190, 220, 370, 30);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Andale Mono", 0, 13)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 290, 90, 30);

        labelBackground.setBackground(new java.awt.Color(0, 0, 102));
        labelBackground.setForeground(new java.awt.Color(204, 204, 204));
        labelBackground.setOpaque(true);
        getContentPane().add(labelBackground);
        labelBackground.setBounds(0, 0, 620, 410);

        setSize(new java.awt.Dimension(614, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        validateAndLogin();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelwelcome;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void validateAndLogin() {
        if(txtUsername.getText().equals("admin") && txtPassword.getText().equals("password")) {
            dispose();
            new MainMenu().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Credentials","Login Failed !",JOptionPane.ERROR_MESSAGE);
         }
    }
}
